# https://github.com/AliAlmasi/react-vite-extension-template/blob/main/.github/workflows/build.yml
name: Build and upload release for Chrome and Firefox

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Zip Chrome build
        run: |
          cd dist
          zip -r chromium-mv3.zip mv3

      - name: Zip Firefox build
        run: |
          cd dist
          zip -r firefox-mv2.zip mv2

      - name: Upload to release (tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/chromium-mv3.zip
            dist/firefox-mv2.zip
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
